export const authConstants = {
  LOGIN_CONFIRM_SUCCESS: "LOGIN_CONFIRM_SUCCESS",
  LOGIN_CONFIRM_FAIL: "LOGIN_CONFIRM_FAIL",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAIL: "LOGOUT_FAIL",
  SIGNUP_LOGIN_SUCCESS: "SIGNUP_LOGIN_SUCCESS",
  SIGNUP_LOGIN_FAIL: "SIGNUP_LOGIN_FAIL",
};

export const alertConstants = {
  ALERT_SET: "ALERT_SET",
  ALERT_REMOVE: "ALERT_REMOVE",
};
